name: medlike
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^4.2.1
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  lottie: ^1.3.0
  mask_text_input_formatter: ^2.3.0
  dio: ^4.0.6
  json_annotation: ^4.5.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: any
  intl: ^0.17.0
  freezed_annotation: ^2.0.3
  skeletons: ^0.0.3
#  flutter_styled_toast: ^2.0.0
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.3
  table_calendar: ^3.0.6
  crypto: ^3.0.2
  flutter_slidable: ^1.3.0
  webview_flutter: ^3.0.4
  carousel_slider: ^4.1.1
  open_file: ^3.2.1
  path_provider: ^2.0.11
  file_picker: ^4.6.1
  image_picker: ^0.8.5+3
  barcode: ^2.2.1
  mime: ^1.0.2
  syncfusion_flutter_charts: ^20.2.40
  cupertino_will_pop_scope: ^1.2.1
  device_info_plus: ^4.0.0
  local_auth: ^2.1.2
  map: ^1.3.3
  cached_network_image: ^3.2.1
  yandex_geocoder: ^2.0.2
  map_launcher: ^2.3.0+1
  collection: ^1.16.0
  tap_canvas: ^0.9.4

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  logger: ^1.1.0

  flutter_lints: any
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  fonts:
    - family: Muller
      fonts:
        - asset: assets/fonts/muller/Fontfabric-Muller-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/muller/Fontfabric-Muller-Light.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/muller/Fontfabric-Muller-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/muller/Fontfabric-Muller-Regular.ttf
          style: normal
          weight: 400
    - family: AquawaxPro
      fonts:
        - asset: assets/fonts/aquawax_pro/AquawaxPro-Bold.otf
          style:  normal
          weight: 700
        - asset: assets/fonts/aquawax_pro/AquawaxPro-Light.otf
          style: normal
          weight: 400
        - asset: assets/fonts/aquawax_pro/AquawaxPro-Medium.otf
          style: normal
          weight: 500
        - asset: assets/fonts/aquawax_pro/AquawaxPro-Regular.otf
          style: normal
          weight: 400
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/icons/menu_icons/
    - assets/icons/bottom_nav_bar/
    - assets/icons/profile/
    - assets/icons/app_bar/
    - assets/icons/subscribe/
    - assets/icons/services/
    - assets/icons/main_page/
    - assets/icons/settings/
    - assets/icons/clinics/
    - assets/icons/appointments/
    - assets/icons/login/
    - assets/icons/medcard/

flutter_intl:
  main_locale: ru_RU
  enabled: true