name: medlike
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^3.2.4
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  lottie: ^1.3.0
  mask_text_input_formatter: ^2.3.0
  dio: ^4.0.6
  json_annotation: ^4.5.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: any
  intl: ^0.17.0
  freezed_annotation: ^2.0.3
  skeletons: ^0.0.3
#  flutter_styled_toast: ^2.0.0
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.3
  table_calendar: ^3.0.6
  crypto: ^3.0.2
  flutter_slidable: ^1.3.0
  yandex_mapkit: ^3.0.2
  yandex_geocoder: ^2.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  logger: ^1.1.0

  flutter_lints: any
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  fonts:
    - family: Muller
      fonts:
        - asset: assets/fonts/muller/Fontfabric-Muller-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/muller/Fontfabric-Muller-Light.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/muller/Fontfabric-Muller-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/muller/Fontfabric-Muller-Regular.ttf
          style: normal
          weight: 400
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/icons/menu_icons/
    - assets/icons/bottom_nav_bar/
    - assets/icons/profile/
    - assets/icons/app_bar/
    - assets/icons/subscribe/
    - assets/icons/services/
    - assets/icons/main_page/
    - assets/icons/settings/
    - assets/icons/clinics/
    - assets/icons/appointments/
    - assets/icons/login/

flutter_intl:
  main_locale: ru_RU
  enabled: true