// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyFZ7wnuA8OBcq5GgD5bJvANEf2YpXxw8',
    appId: '1:1083145779008:web:9911fb9cd9d55d9d742ca5',
    messagingSenderId: '1083145779008',
    projectId: 'z-clinic-flutter-project',
    authDomain: 'z-clinic-flutter-project.firebaseapp.com',
    storageBucket: 'z-clinic-flutter-project.appspot.com',
    measurementId: 'G-2QW4MXF96V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqIHlQlHTa4omDCLDIc4qZnW7RHhKw6Y4',
    appId: '1:1083145779008:android:487e71139690f03c742ca5',
    messagingSenderId: '1083145779008',
    projectId: 'z-clinic-flutter-project',
    storageBucket: 'z-clinic-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAqkajsf-AA3mZ8iWInLMukxyLUCqSJcw',
    appId: '1:1083145779008:ios:8ba106478404758c742ca5',
    messagingSenderId: '1083145779008',
    projectId: 'z-clinic-flutter-project',
    storageBucket: 'z-clinic-flutter-project.appspot.com',
    iosClientId: '1083145779008-128t6iagq182gbf2k702uo0066ot8t50.apps.googleusercontent.com',
    iosBundleId: 'com.example.medlike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAqkajsf-AA3mZ8iWInLMukxyLUCqSJcw',
    appId: '1:1083145779008:ios:8ba106478404758c742ca5',
    messagingSenderId: '1083145779008',
    projectId: 'z-clinic-flutter-project',
    storageBucket: 'z-clinic-flutter-project.appspot.com',
    iosClientId: '1083145779008-128t6iagq182gbf2k702uo0066ot8t50.apps.googleusercontent.com',
    iosBundleId: 'com.example.medlike',
  );
}
