import 'package:medlike/data/models/document_models/document_models.dart';

List<DocumentModel> documentsMock = [
  DocumentModel(
    documentName: 'Дополнительное соглашение к договору №1',
    documentURL: 'documentURL',
    status: 4,
    clinicAddress: '“Наименование клиники №1” ул. Октябрьская, 24Б',
    documentSubscribeDate: DateTime(2022),
    documentCreateDate: DateTime(2021),
    userName: 'Екатерина К.',
  ),
  DocumentModel(
    documentName: 'Пользовательское соглашение',
    documentURL: 'documentURL',
    status: 1,
    clinicAddress: '“Наименование клиники №1” ул. Октябрьская, 24Б',
    documentSubscribeDate: DateTime(2022),
    documentCreateDate: DateTime(2021),
    userName: 'Екатерина К.',
  ),
  DocumentModel(
    documentName: 'Дополнительное соглашение к договору №1',
    documentURL: 'documentURL',
    status: 2,
    clinicAddress: '“Наименование клиники №1” ул. Октябрьская, 24Б',
    documentSubscribeDate: DateTime(2022),
    documentCreateDate: DateTime(2021),
    userName: 'Екатерина К.',
  ),
  DocumentModel(
    documentName:
        'Дополнительное соглашение к договору №1 Дополнительное соглашение к договору №1',
    documentURL: 'documentURL',
    status: 3,
    clinicAddress: '“Наименование клиники №1” ул. Октябрьская, 24Б',
    documentSubscribeDate: DateTime(2022),
    documentCreateDate: DateTime(2021),
    userName: 'Екатерина К.',
  ),
  DocumentModel(
    documentName: 'Дополнительное соглашение к договору №1',
    documentURL: 'documentURL',
    status: 1,
    clinicAddress: '“Наименование клиники №1” ул. Октябрьская, 24Б',
    documentSubscribeDate: DateTime(2022),
    documentCreateDate: DateTime(2021),
    userName: 'Екатерина К.',
  ),
  DocumentModel(
    documentName: 'Дополнительное соглашение к договору №1',
    documentURL: 'documentURL',
    status: 4,
    clinicAddress: '“Наименование клиники №1” ул. Октябрьская, 24Б',
    documentSubscribeDate: DateTime(2022),
    documentCreateDate: DateTime(2021),
    userName: 'Екатерина К.',
  ),
  DocumentModel(
    documentName: 'Дополнительное соглашение к договору №1',
    documentURL: 'documentURL',
    status: 2,
    clinicAddress: '“Наименование клиники №1” ул. Октябрьская, 24Б',
    documentSubscribeDate: DateTime(2022),
    documentCreateDate: DateTime(2021),
    userName: 'Екатерина К.',
  ),
  DocumentModel(
    documentName: 'Дополнительное соглашение к договору №1',
    documentURL: 'documentURL',
    status: 3,
    clinicAddress: '“Наименование клиники №1” ул. Октябрьская, 24Б',
    documentSubscribeDate: DateTime(2022),
    documentCreateDate: DateTime(2021),
    userName: 'Екатерина К.',
  ),
];
